site_name: Bradford 2025 data pipelines
site_url: https://bradford-2025.github.io/data

theme:
  name: material
  palette:
    primary: black
  font:
    text: Denim INK
  logo: assets/logo.svg

extra_css:
  - assets/fonts/denim-ink.css

plugins:
  - search
  - mermaid2:
      version: 11.1.0
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true
            show_submodules: true
            # parameter_headings: true
            show_signature: true
            separate_signature: false
            inherited_members: true
            show_symbol_type_toc: true
          paths:
          #   - ./
            - upstream/pipelines
            - upstream/scripts
  - mkdocs-jupyter:
      include: ["*.ipynb"] # Default: ["*.py", "*.ipynb"]
  - include-markdown
# watch:
#   - upstream

nav:
  - Introduction: index.md
  - overview.md

  - Data:
    - Datasets: datasets/index.md
    - Publishing: process/publishing.md

  - Pipelines:
      - Overview: pipelines.md
      - Operational Systems:
        - Airtable:
          - pipelines/programme.ipynb
          - pipelines/cultural-learning.ipynb
          - pipelines/digital-followers.ipynb
          - pipelines/sustainability.ipynb
        - Spektrix:
          - pipelines/ticketing.ipynb
        - Spreadsheets:
          - pipelines/audience-survey.ipynb
          - pipelines/manual_data_feeds.ipynb
        - Rosterfy:
          - pipelines/volunteer-people.ipynb
          - pipelines/volunteer-shift.ipynb
        - Google Analytics:
          - pipelines/digital-events.ipynb
          - pipelines/digital-audience.ipynb
      
      - Preparation and Publication:
        - pipelines/combine.ipynb
        - pipelines/publish.ipynb

      - Utilities:
        - pipelines/status.ipynb
        - pipelines/catalogue.ipynb
        - pipelines/reports.ipynb

      # - Reports:
      #   - pipelines/reports/ticketing.ipynb
      #   - pipelines/reports/volunteer-postcode.ipynb
  - Reference:
    - Overview: reference.md
    - reference/processing.md
    - reference/utilities.md
  # - tutorials.md

  - How-to guides: how-to-guides.md

  - Architecture:
      - Overview: architecture/overview.md


repo_url: https://github.com/bradford-2025/data/

markdown_extensions:
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

hooks:
  - hooks/copy_pipeline_files.py

